import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-background";
import Navbar from "@/components/ui/navbar";
import { BentoGrid } from "@/components/ui/bento-grid";
import { BentoGridSecond } from "./bento-grid/page";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} } antialiased`}
      >
        <AuroraBackground>
          <Navbar />
          {children}
          
        </AuroraBackground>
        <BentoGrid>
          <BentoGridSecond />
        </BentoGrid>
      </body>
    </html>
  );
}