import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-background";
import Navbar from "@/components/ui/navbar";
import WobbleCardDemo from "@/components/ui/wobble-card-demo";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} } antialiased`}>
        <AuroraBackground>
          <Navbar />
          {children}
        </AuroraBackground>
        <div className="text-center py-20">
          <h2 className="text-4xl font-bold mb-4">Features</h2>
          <p className="text-xl text-gray-600 mb-8">Our Aim is to provide exceptional UI components for modern web development</p>
        </div>
        <WobbleCardDemo />
      </body>
    </html>
  );
}